
baseURL ="https://saad-aamir.github.io/presentation-site"
publishDir="docs"

languageCode = "en-us"
title = "OS Assignment"
theme="ananke"


[markup]

   [markup.goldmark]

	[markup.goldmark.renderer]
	unsafe=true



SectionPagesMenu = "main"
[params]
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = "https://twitter.com/GoHugoIO"
  instagram = "https://www.instagram.com/saadaamir.__/"
  youtube = ""
  github = "https://github.com/saad-aamir"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/lol7.jpg"
  recent_posts_number = 2


